### ISSUE TITLE
Integrating with latest version of meanjs from yeoman generator?

### ISSUE THREAD

**Issue by quanzix** [marc-harry/meanjs-ngflow#1]
Beating my head against the wall for a few days now to get ngflow integrated and working (both front end and backend) from yo meanjs implementation.

Would greatly appreciate help and instructions...

**Comment by marc-harry** [comment]
If your having issues setting up this project so steps missed out in the readme file are that you need to run from the source directory you also need to have mongo db setup on you development machine: 
`npm install -g grunt bower`
`npm install`
`npm install grunt`
`bower install`
and finally `grunt`

You should then have a successfully running application.

**Comment by quanzix** [comment]
Hi Marc, thanks for getting back. Don't get me wrong, your implementation
works perfect. What I'm trying to do is to use latest version of meanjs
generator from yeoman and integrate Ngflow. My problem was that when it
came to processing the upload.create function of he server controller the
req.body or req.files was undefined. I looked into other implementations of
flow.js and added multipart middleware to the .post method of the app.route
(in routers). That enabled req.body and req.files so I have information
from the request to save to mongodb. I also call flow.post function on
server side to save file chunks. I don't see flow.post in your
implementation so it really beats me to understand how you are actually
saving file on the server side... It works for me now, I can't however
control the name of the physical file saved on the server with flow.post.
If any of that makes any sense...

To add to the problem I'm actually looking for an image uploader for meanjs
that is able to resize image on the fly. Any suggestions?

Thanks a lot for your time and effort!

**Comment by marc-harry** [comment]
In the file config/express.js I imported and setup a package called 'multer' which allows you do do `app.use(multer({dest: './public/uploads/'}));` and that is where it puts the content of the files. That was the extent to which I was storing the files and in MongoDB I was just storing the to file location as a string. 

Unfortunately I have not used any image resizing frameworks in nodejs so I don't have any recommendations in that regard sorry.

**Comment by quanzix** [comment]
Thanks Marc! So the only thing to enable storing file content would be to
include multer package and this line in express.js? I actually stumbled
upon this line, trying to figure out what does multer do, but not quite
sure where the magic happens in actually processing and storing the content
of the file? Upload.create stores the info in mongodb, what is the flow on
where the request to store the physical file content is executed?

Appreciate your collaboration!

**Comment by marc-harry** [comment]
Yes just that package and setup line are all thats needed to store the file. I believe the flow to store the physical file takes place within the multer framework which hooks into express.js as middleware and then stores the file and populates the req.files property following a multipart request.

**Comment by quanzix** [comment]
Awesome, thanks! Will try that!

Thanks again!

**Comment by marc-harry** [comment]
No problem.
